import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/pricing">Pricing</Link>
        </li>
        <li>
          <Link to="/pticing">Pticing</Link>
        </li>
        <li>
          <Link to="/clientdashboard">ClientDashboard</Link>
        </li>
        <li>
          <Link to="/notificationtwelve">NotificationTwelve</Link>
        </li>
        <li>
          <Link to="/pricingone">PricingOne</Link>
        </li>
        <li>
          <Link to="/landingpage">LANDINGPAGE</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/landingpageone">LANDINGPAGEOne</Link>
        </li>
        <li>
          <Link to="/document">Document</Link>
        </li>
        <li>
          <Link to="/pdfdocx">Pdfdocx</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/forgetpassword">Forgetpassword</Link>
        </li>
        <li>
          <Link to="/applicationdetails">Applicationdetails</Link>
        </li>
        <li>
          <Link to="/cardpaymentflow">CardPaymentFlow</Link>
        </li>
        <li>
          <Link to="/cardpin">CardPin</Link>
        </li>
        <li>
          <Link to="/cardloadinganimation">CardLoadinganimation</Link>
        </li>
        <li>
          <Link to="/cardordercomplete">CardOrdercomplete</Link>
        </li>
        <li>
          <Link to="/bankpaymentflow">BankPaymentFlow</Link>
        </li>
        <li>
          <Link to="/dropdown">Dropdown</Link>
        </li>
        <li>
          <Link to="/accountnumberdetails">AccountNumberDetails</Link>
        </li>
        <li>
          <Link to="/bankloadinganimation">BankLoadinganimation</Link>
        </li>
        <li>
          <Link to="/bankordercomplete">BankOrdercomplete</Link>
        </li>
        <li>
          <Link to="/transferpaymentflow">TransferPaymentFlow</Link>
        </li>
        <li>
          <Link to="/transferloadinganimation">TransferLoadinganimation</Link>
        </li>
        <li>
          <Link to="/transferordercomplete">TransferOrdercomplete</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
